[project]
name = "pipelines"
version = "0.1.0"
description = "Data processing pipelines"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect[gcp]>=3.4.14",
]

[tool.setuptools]
packages = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
